IF2015/Models/Mahasiswa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace IF2015.Models
{

    public class Mahasiswa
    {
        [Key]
        public int id { get; set; }

        public string nama_mahasiswa { get; set; }

        [DataType(DataType.Date)]
        public DateTime? tanggal_lahir { get; set; }

        public string jenis_kelamin { get; set; }

        public int id_hobi { get; set; }
    }
}

IF2015/Controllers/MahasiswaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IF2015.Models;
using System.Linq.Dynamic.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IF2015.Controllers
{
    public class MahasiswaController : Controller
    {
        private readonly BazingaContext context;

        public MahasiswaController(BazingaContext context)
        {
            this.context = context;
        }

        [HttpPost]
        public IActionResult GetMahasiswaList()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;
                var query = (from mhs in context.mahasiswa
                            select new
                            {
                                id = mhs.id,
                                nama_mahasiswa = mhs.nama_mahasiswa,
                                tanggal_lahir = mhs.tanggal_lahir,
                                jenis_kelamin = mhs.jenis_kelamin,
                                id_hobi = (from hobi in context.hobi where hobi.id == mhs.id_hobi select hobi.nama_hobi).FirstOrDefault(),
                            });
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    query = query.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                if (!string.IsNullOrEmpty(searchValue))
                {
                    query = query.Where(m => m.nama_mahasiswa.Contains(searchValue)
                                            || m.id_hobi.Contains(searchValue)
                                        );
                }
                recordsTotal = query.Count();
                var data = query.Skip(skip).Take(pageSize).ToList();
                var jsonData = new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data };
                return Ok(jsonData);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Index()
        {
            ViewData["Datatables"] = "ya";

            return View();
        }


        //Method for create form
        public IActionResult Create()
        {
            var model = new Mahasiswa();
            ViewBag.Hobi = context.hobi.ToList();
            return PartialView("CreateEdit", model);
        }

        //Get data by ID
        public IF2015.Models.Mahasiswa GetByID(int ID)
        {
            return context.mahasiswa.Where(e => e.id == ID).FirstOrDefault();
        }

        //Method for edit form
        public IActionResult Edit(int ID)
        {
            var inputPassing = new Mahasiswa();
            var existData = GetByID(ID);

            if (existData != null)
            {
                inputPassing.id = existData.id;
                inputPassing.nama_mahasiswa = existData.nama_mahasiswa;
                inputPassing.tanggal_lahir = existData.tanggal_lahir;
                inputPassing.jenis_kelamin = existData.jenis_kelamin;
                inputPassing.id_hobi = existData.id_hobi;
            }

            ViewBag.Hobi = context.hobi.ToList();
            return PartialView("CreateEdit", inputPassing);
        }

        [HttpPost]
        //Execute create / edit
        public IActionResult CreateEdit(Mahasiswa inputValue)
        {
            string message;
            if (inputValue.id == 0)
            {
                var mhs = new IF2015.Models.Mahasiswa();
                mhs.nama_mahasiswa = inputValue.nama_mahasiswa;
                mhs.tanggal_lahir = inputValue.tanggal_lahir;
                mhs.jenis_kelamin = inputValue.jenis_kelamin;
                mhs.id_hobi = inputValue.id_hobi;
                context.Add(mhs);
                context.SaveChanges();
                message = "Saved";
            }
            else
            {
                var existData = GetByID(inputValue.id);

                if (existData != null)
                {
                    existData.nama_mahasiswa = inputValue.nama_mahasiswa;
                    existData.tanggal_lahir = inputValue.tanggal_lahir;
                    existData.jenis_kelamin = inputValue.jenis_kelamin;
                    existData.id_hobi = inputValue.id_hobi;
                    context.Update(existData);
                    context.SaveChanges();
                    message = "Updated";
                }
                else
                {
                    message = "Data not found";
                }
            }
            return Json(message);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var result = "";

            if (id != null)
            {
                context.mahasiswa.Remove(context.mahasiswa.Find(id));
                context.SaveChanges();
                result = "Deleted";
            }
            else
            {
                result = "Data not found";
            }

            return Json(result);
        }

    }
}

IF2015/Views/Mahasiswa/CreateEdit.cshtml
@model IF2015.Models.Mahasiswa


<div class="modal-header">
    <h4 class="text-left">Add Mahasiswa</h4>
    <!-- <h4 class="custom-modal-title">Menu</h4> -->
</div>
<form id="frmCreateEdit">
    <input name="id" type="hidden" id="id" value="@Model.id" />
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">Nama Mahasiswa</span>
                        <input required asp-for="nama_mahasiswa" name="nama_mahasiswa" class="form-control" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">Tangga Lahir</span>
                        <input required asp-for="tanggal_lahir" name="tanggal_lahir" class="form-control" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">Jenis Kelamin</span>
                        <input style="margin-left: 10px;" required type="radio" asp-for="jenis_kelamin" name="jenis_kelamin" value="L" /> Pria
                        <input type="radio" asp-for="jenis_kelamin" name="jenis_kelamin" value="P" /> Wanita
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">Hobi</span>
                        <select id="hobi" asp-for="id_hobi" name="id_hobi" class="form-control" asp-items="@(new SelectList(ViewBag.Hobi, "id", "nama_hobi"))" required><option value="">--- Select Hobi ---</option></select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-info col-lg-12" id="btnSubmit">Save</button>
    </div>
</form>


<script>

    $(document).ready(function () {
        $('#hobi').select2({
            placeholder: "--- Select Hobi ---",
            dropdownParent: $("#CreateEdit")
        });
    })

    $("#frmCreateEdit").on("submit", function (e) {
        e.preventDefault();
        
        $.ajax({
            url: "@Url.Action("CreateEdit","Mahasiswa")",
            type: "POST",
            data: $(this).serialize(),
            success: function (message) {
                if (message == "Saved") {
                    swal("Saved", "Click ok to proceed", "success");
                    tbl_mahasiswa.ajax.reload();
                }
                else if (message == "Updated") {
                    swal("Updated", "Click ok to proceed", "success");
                    tbl_mahasiswa.ajax.reload();
                }
                else {
                    swal({
                        title: "Something Wrong",
                        text: "Something Wrong",
                        type: "error"
                    });
                }
                $("#CreateEdit").modal("hide");
            },
            error: function (data) {
                $("#CreateEdit").modal("hide");
                swal({
                    title: "Error",
                    text: "Error",
                    type: "error"
                });
            }
        });
    });
</script>

IF2015/Views/Mahasiswa/Index.cshtml
@model IEnumerable<IF2015.Models.Mahasiswa>

@{
    ViewData["Title"] = "Mahasiswa IF 2015";
}

@section tambahan_css_plugins {
    <link href="~/plugins/dropify/dist/css/dropify.min.css" rel="stylesheet" type="text/css" />
    <style>
        table.dataTable thead > tr > th.th-number {
            padding-left: 8px;
            padding-right: 8px;
        }
    </style>
}

<div class="row">
    <div class="col-12">
        <div class="card-box">
            <div class="well text-center" style="padding: 5px">
                <label>
                    Mahasiswa IF 2015
                </label>
            </div>

            <div class="row">
                <div class="col-sm-12 m-b-15">
                    <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#CreateEdit" onclick="CreateEdit(0);">
                        <i class="fa fa-plus" aria-hidden="true"></i> Add Mahasiswa
                    </button>
                </div>
            </div>

            <table class="table table-striped table-responsive" id="tbl_mahasiswa">
                <thead>
                    <tr>
                        <th class="text-center th-number">No.</th>
                        <th class="text-center">Nama Mahasiswa</th>
                        <th class="text-center">Tanggal Lahir</th>
                        <th class="text-center">Jenis Kelamin</th>
                        <th class="text-center">Hobi</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>

            </table>
        </div>
    </div><!-- end col -->
</div>
<!-- end row -->

<div id="CreateEdit" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="divModal">

        </div>
    </div>
</div>

@section tambahan_js {
    <script type="text/javascript">

        function CreateEdit(id)
        {
            if (id == 0) {
                url = "@Url.Action("Create","Mahasiswa")";
            }
            else {
                url = "@Url.Action("Edit", "Mahasiswa")/" + id;
            }

            $.ajax({
                url: url,
                type: "GET",
                success: function(data){
                    $("#divModal").html(data);
                },
                error: function (data) {
                    alert('Call Admin for help !');
                }
            });
        }

        //Datatable Mahasiswa
        var tbl_mahasiswa = $("#tbl_mahasiswa").DataTable({
            "processing": true, // A boolean property that when enables shows the processing indicator when the table is being processed.
            "serverSide": true, // This property enables server-side processing
            "filter": true, // enables/disables the search bar.
            "ajax": { //used to fetch the data from external sources, in our case, API
                "url": "/Mahasiswa/GetMahasiswaList",
                "type": "POST",
                "datatype": "json"
            },
            "columnDefs": [{
                "targets": 2,
                "render": function (data) {
                    return moment(data).format('D MMMM YYYY');
                }
            }
            ],
            "order": [[1, "asc"]],
            "columns": [
                //It is important to use camelCasing while defining the names of the variables.displayName will work.
                //But DisplayName won’t.Quite weird, but that’s how js works.Make sure you follow camelCasing standard while working with js scripts
                { "data": null, "orderable": false, "searchable": false, "sClass": "text-center", "width": "7%" },
                { "data": "nama_mahasiswa", "name": "nama_mahasiswa", "autoWidth": true },
                { "data": "tanggal_lahir", "name": "tanggal_lahir", "autoWidth": true },
                { "data": "jenis_kelamin", "name": "jenis_kelamin", "autoWidth": true },
                { "data": "id_hobi", "name": "id_hobi", "autoWidth": true },
                {
                    "sortable": false,
                    "render": function (data, type, row) {
                        return "<button class='btn btn-info btn-sm' data-toggle='modal' data-target='#CreateEdit' onclick=CreateEdit('" + row.id + "');><i class='fa fa-edit' aria-hidden='true'></i></button><button style='margin-left: 5px;' class='btn btn-sm btn-danger' onclick=deleteData('" + row.id + "'); ><i class='fa fa-trash' aria-hidden='true'></i></button>"
                    }
                },
            ]
        });

        tbl_mahasiswa.on('draw.dt', function () {
            var PageInfo = $('#tbl_mahasiswa').DataTable().page.info();
            tbl_mahasiswa.column(0, { page: 'current' }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1 + PageInfo.start;
            });
        });

        function deleteData(id)
        {
            swal({
                title: "Are you sure?",
                text: "Delete this data",
                showCancelButton: true,
                cancelButtonColor: "#c0392b",
                confirmButtonColor: "#c0392b",
                confirmButtonText: "Yes",
                cancelButtonText: 'Cancel',
                animation: true,
                allowEscapeKey: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
                html: true
            },
                function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            type: "POST",
                            url: "@Url.Action("Delete","Mahasiswa")",
                            data: {
                                ID: id
                            },
                            traditional: true,
                            success: function (result) {

                                if (result == "Deleted") {
                                    swal("Deleted", "Click ok to proceed", "success");
                                    tbl_mahasiswa.ajax.reload();
                                } else {
                                    swal({
                                        title: "Something Wrong",
                                        text: result.message,
                                        type: "error"
                                    });
                                }
                            },
                            error: function (result) {
                                swal({
                                    title: "Error",
                                    text: "Delete error",
                                    type: "error"
                                });
                            }
                        });
                    }
                });

        }
    </script>

}