IF2015/Models/Hobi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace IF2015.Models
{

    public class Hobi
    {
        [Key]
        public int id { get; set; }
        public string nama_hobi { get; set; }
    }
}

IF2015/Controllers/HobiController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IF2015.Models;
using IF2015.ModelsAPI;
using System.Linq.Dynamic.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http;

namespace IF2015.Controllers
{
    public class HobiController : Controller
    {
        private readonly BazingaContext context;

        public HobiController(BazingaContext context)
        {
            this.context = context;
        }

        [HttpPost]
        public IActionResult GetHobiList()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;
                var query = (from hobi in context.hobi
                            select new
                            {
                                id = hobi.id,
                                nama_hobi = hobi.nama_hobi,
                            });
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    query = query.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                if (!string.IsNullOrEmpty(searchValue))
                {
                    query = query.Where(m => m.nama_hobi.Contains(searchValue));
                }
                recordsTotal = query.Count();
                var data = query.Skip(skip).Take(pageSize).ToList();
                var jsonData = new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data };
                return Ok(jsonData);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Index()
        {
            ViewData["Datatables"] = "ya";

            return View();
        }


        //Method for create form
        public IActionResult Create()
        {
            var model = new Hobi();

            IEnumerable<HobiAPI> hobiList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("https://localhost:44309/api/RatingHobbyAPI/GetAllData").Result;
            hobiList = response.Content.ReadAsAsync<IEnumerable<HobiAPI>>().Result;
            ViewBag.Hobi = hobiList;

            return PartialView("CreateEdit", model);
        }

        //Get data by ID
        public IF2015.Models.Hobi GetByID(int ID)
        {
            return context.hobi.Where(e => e.id == ID).FirstOrDefault();
        }

        //Method for edit form
        public IActionResult Edit(int ID)
        {
            var inputPassing = new Hobi();
            var existData = GetByID(ID);

            if (existData != null)
            {
                inputPassing.id = existData.id;
                inputPassing.nama_hobi = existData.nama_hobi;
            }

            IEnumerable<HobiAPI> hobiList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("https://localhost:44309/api/RatingHobbyAPI/GetAllData").Result;
            hobiList = response.Content.ReadAsAsync<IEnumerable<HobiAPI>>().Result;
            ViewBag.Hobi = hobiList;

            return PartialView("CreateEdit", inputPassing);
        }

        [HttpPost]
        //Execute create / edit
        public IActionResult CreateEdit(Hobi inputValue)
        {
            string message;
            if (inputValue.id == 0)
            {
                var mhs = new IF2015.Models.Hobi();
                mhs.nama_hobi = inputValue.nama_hobi;
                context.Add(mhs);
                context.SaveChanges();
                message = "Saved";
            }
            else
            {
                var existData = GetByID(inputValue.id);

                if (existData != null)
                {
                    existData.nama_hobi = inputValue.nama_hobi;
                    context.Update(existData);
                    context.SaveChanges();
                    message = "Updated";
                }
                else
                {
                    message = "Data not found";
                }
            }
            return Json(message);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var result = "";

            if (id != null)
            {
                context.hobi.Remove(context.hobi.Find(id));
                context.SaveChanges();
                result = "Deleted";
            }
            else
            {
                result = "Data not found";
            }

            return Json(result);
        }

    }
}

IF2015/Views/Hobi/CreateEdit.cshtml
@model IF2015.Models.Hobi


<div class="modal-header">
    <h4 class="text-left">Add Hobi</h4>
    <!-- <h4 class="custom-modal-title">Menu</h4> -->
</div>
<form id="frmCreateEdit">
    <input name="id" type="hidden" id="id" value="@Model.id" />
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">Hobi</span>
                        <select id="hobi" asp-for="nama_hobi" name="nama_hobi" class="form-control" asp-items="@(new SelectList(ViewBag.Hobi, "hobby_name", "hobby_name"))" required><option value="">--- Select Hobi ---</option></select>
                    </div>
                </div>       
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-info col-lg-12" id="btnSubmit">Save</button>
    </div>
</form>


<script>
    $(document).ready(function () {
        $('#hobi').select2({
            placeholder: "--- Select Hobi ---",
            dropdownParent: $("#CreateEdit")
        });
    })

    $("#frmCreateEdit").on("submit", function (e) {
        e.preventDefault();
        
        $.ajax({
            url: "@Url.Action("CreateEdit","Hobi")",
            type: "POST",
            data: $(this).serialize(),
            success: function (message) {
                if (message == "Saved") {
                    swal("Saved", "Click ok to proceed", "success");
                    tbl_hobi.ajax.reload();
                }
                else if (message == "Updated") {
                    swal("Updated", "Click ok to proceed", "success");
                    tbl_hobi.ajax.reload();
                }
                else {
                    swal({
                        title: "Something Wrong",
                        text: "Something Wrong",
                        type: "error"
                    });
                }
                $("#CreateEdit").modal("hide");
            },
            error: function (data) {
                $("#CreateEdit").modal("hide");
                swal({
                    title: "Error",
                    text: "Error",
                    type: "error"
                });
            }
        });
    });
</script>

IF2015/Views/Hobi/Index.cshtml
@model IEnumerable<IF2015.Models.Hobi>

@{
    ViewData["Title"] = "Hobi";
}

@section tambahan_css_plugins {
    <link href="~/plugins/dropify/dist/css/dropify.min.css" rel="stylesheet" type="text/css" />
    <style>
        table.dataTable thead > tr > th.th-number {
            padding-left: 8px;
            padding-right: 8px;
        }
    </style>
}

<div class="row">
    <div class="col-12">
        <div class="card-box">
            <div class="well text-center" style="padding: 5px">
                <label>
                    Hobi
                </label>
            </div>

            <div class="row">
                <div class="col-sm-12 m-b-15">
                    <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#CreateEdit" onclick="CreateEdit(0);">
                        <i class="fa fa-plus" aria-hidden="true"></i> Add Hobi
                    </button>
                </div>
            </div>

            <table class="table table-striped table-responsive" id="tbl_hobi">
                <thead>
                    <tr>
                        <th class="text-center th-number">No.</th>
                        <th class="text-center">Nama Hobi</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>

            </table>
        </div>
    </div><!-- end col -->
</div>
<!-- end row -->

<div id="CreateEdit" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="divModal">

        </div>
    </div>
</div>

@section tambahan_js {
    <script type="text/javascript">

        function CreateEdit(id)
        {
            if (id == 0) {
                url = "@Url.Action("Create","Hobi")";
            }
            else {
                url = "@Url.Action("Edit", "Hobi")/" + id;
            }

            $.ajax({
                url: url,
                type: "GET",
                success: function(data){
                    $("#divModal").html(data);
                },
                error: function (data) {
                    alert('Call Admin for help !');
                }
            });
        }

        //Datatable Hobi
        var tbl_hobi = $("#tbl_hobi").DataTable({
            "processing": true, // A boolean property that when enables shows the processing indicator when the table is being processed.
            "serverSide": true, // This property enables server-side processing
            "filter": true, // enables/disables the search bar.
            "ajax": { //used to fetch the data from external sources, in our case, API
                "url": "/Hobi/GetHobiList",
                "type": "POST",
                "datatype": "json"
            },
            "order": [[1, "asc"]],
            "columns": [
                //It is important to use camelCasing while defining the names of the variables.displayName will work.
                //But DisplayName won’t.Quite weird, but that’s how js works.Make sure you follow camelCasing standard while working with js scripts
                { "data": null, "orderable": false, "searchable": false, "sClass": "text-center", "width": "7%" },
                { "data": "nama_hobi", "name": "nama_hobi", "autoWidth": true },
                {
                    "sortable": false,
                    "render": function (data, type, row) {
                        return "<button class='btn btn-info btn-sm' data-toggle='modal' data-target='#CreateEdit' onclick=CreateEdit('" + row.id + "');><i class='fa fa-edit' aria-hidden='true'></i></button><button style='margin-left: 5px;' class='btn btn-sm btn-danger' onclick=deleteData('" + row.id + "'); ><i class='fa fa-trash' aria-hidden='true'></i></button>"
                    }
                },
            ]
        });

        tbl_hobi.on('draw.dt', function () {
            var PageInfo = $('#tbl_hobi').DataTable().page.info();
            tbl_hobi.column(0, { page: 'current' }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1 + PageInfo.start;
            });
        });

        function deleteData(id)
        {
            swal({
                title: "Are you sure?",
                text: "Delete this data",
                showCancelButton: true,
                cancelButtonColor: "#c0392b",
                confirmButtonColor: "#c0392b",
                confirmButtonText: "Yes",
                cancelButtonText: 'Cancel',
                animation: true,
                allowEscapeKey: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
                html: true
            },
                function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            type: "POST",
                            url: "@Url.Action("Delete","Hobi")",
                            data: {
                                ID: id
                            },
                            traditional: true,
                            success: function (result) {

                                if (result == "Deleted") {
                                    swal("Deleted", "Click ok to proceed", "success");
                                    tbl_hobi.ajax.reload();
                                } else {
                                    swal({
                                        title: "Something Wrong",
                                        text: result.message,
                                        type: "error"
                                    });
                                }
                            },
                            error: function (result) {
                                swal({
                                    title: "Error",
                                    text: "Delete error",
                                    type: "error"
                                });
                            }
                        });
                    }
                });

        }
    </script>

}